import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Modal from './components/Modal'

export const metadata: Metadata = {
  title: 'Kanban board',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='bg-background'>
        {children}
        <Modal />
      </body>
    </html>
  )
}
